// Field assignments and option values read from the Conners 3–Parent scoring grid.
// Both halves of the grid (Part 1: Q1–63, Part 2: Q64–108) map to the same
// 13 combined field keys — no "1"/"2" suffixes.
// Items with fields:[] are screener-only or impairment items.
const questions = [
  // ── Part 1 (Q1–63) ────────────────────────────────────────────
  { id: 1,   fields: ["NI"],             options: [1, 1, 0, 0] },
  { id: 2,   fields: ["AN"],             options: [0, 1, 2, 3] },
  { id: 3,   fields: ["AH"],             options: [0, 1, 2, 3] },
  { id: 4,   fields: [],                 options: [0, 1, 2, 3] },
  { id: 5,   fields: ["LP"],             options: [0, 1, 2, 3] },
  { id: 6,   fields: ["CD"],             options: [0, 1, 2, 3] },
  { id: 7,   fields: ["LP"],             options: [0, 1, 2, 3] },
  { id: 8,   fields: ["NI"],             options: [1, 1, 0, 0] },
  { id: 9,   fields: ["LP"],             options: [3, 2, 1, 0] },
  { id: 10,  fields: ["PR"],             options: [0, 1, 2, 3] },
  { id: 11,  fields: ["CD"],             options: [0, 1, 2, 3] },
  { id: 12,  fields: ["IN"],             options: [0, 1, 2, 3] },
  { id: 13,  fields: ["PR"],             options: [0, 1, 2, 3] },
  { id: 14,  fields: ["OD"],             options: [0, 1, 2, 3] },
  { id: 15,  fields: ["LP"],             options: [0, 1, 2, 3] },
  { id: 16,  fields: ["AG", "CD"],       options: [0, 1, 2, 3] },
  { id: 17,  fields: [],                 options: [0, 1, 2, 3] },
  { id: 18,  fields: ["NI"],             options: [0, 0, 1, 1] },
  { id: 19,  fields: ["HY", "GI"],       options: [0, 1, 2, 3] },
  { id: 20,  fields: [],                 options: [0, 1, 2, 3] },
  { id: 21,  fields: ["OD"],             options: [0, 1, 2, 3] },
  { id: 22,  fields: ["AG"],             options: [0, 1, 2, 3] },
  { id: 23,  fields: ["IN"],             options: [0, 1, 2, 3] },
  { id: 24,  fields: ["PR"],             options: [0, 1, 2, 3] },
  { id: 25,  fields: ["GI"],             options: [0, 1, 2, 3] },
  { id: 26,  fields: ["NI"],             options: [0, 0, 1, 1] },
  { id: 27,  fields: ["AG", "CD"],       options: [0, 1, 2, 3] },
  { id: 28,  fields: ["IN", "AN"],       options: [0, 1, 2, 3] },
  { id: 29,  fields: ["GI"],             options: [0, 1, 2, 3] },
  { id: 30,  fields: ["AG", "CD"],       options: [0, 1, 2, 3] },
  { id: 31,  fields: ["PI"],             options: [1, 0, 0, 0] },
  { id: 32,  fields: ["NI"],             options: [0, 0, 1, 1] },
  { id: 33,  fields: ["PI"],             options: [0, 0, 0, 1] },
  { id: 34,  fields: ["EF", "GI"],       options: [0, 1, 2, 3] },
  { id: 35,  fields: ["AN"],             options: [0, 1, 2, 3] },
  { id: 36,  fields: ["LP"],             options: [0, 1, 2, 3] },
  { id: 37,  fields: ["EF"],             options: [0, 1, 2, 3] },
  { id: 38,  fields: ["PI"],             options: [1, 0, 0, 0] },
  { id: 39,  fields: ["AG", "CD"],       options: [0, 1, 2, 3] },
  { id: 40,  fields: ["GI"],             options: [0, 1, 2, 3] },
  { id: 41,  fields: ["CD"],             options: [0, 1, 2, 3] },
  { id: 42,  fields: ["NI"],             options: [0, 0, 1, 1] },
  { id: 43,  fields: ["HY", "AH"],       options: [0, 1, 2, 3] },
  { id: 44,  fields: ["IN"],             options: [0, 1, 2, 3] },
  { id: 45,  fields: ["HY", "AH"],       options: [0, 1, 2, 3] },
  { id: 46,  fields: ["AG"],             options: [0, 1, 2, 3] },
  { id: 47,  fields: ["IN", "AN"],       options: [0, 1, 2, 3] },
  { id: 48,  fields: ["AG", "OD"],       options: [0, 1, 2, 3] },
  { id: 49,  fields: ["IN"],             options: [0, 1, 2, 3] },
  { id: 50,  fields: ["GI"],             options: [0, 1, 2, 3] },
  { id: 51,  fields: ["LP"],             options: [0, 1, 2, 3] },
  { id: 52,  fields: ["HY"],             options: [0, 1, 2, 3] },
  { id: 53,  fields: ["LP"],             options: [0, 1, 2, 3] },
  { id: 54,  fields: ["HY", "AH"],       options: [0, 1, 2, 3] },
  { id: 55,  fields: ["HY"],             options: [0, 1, 2, 3] },
  { id: 56,  fields: ["CD"],             options: [0, 1, 2, 3] },
  { id: 57,  fields: ["AG", "OD"],       options: [0, 1, 2, 3] },
  { id: 58,  fields: ["AG", "CD"],       options: [0, 1, 2, 3] },
  { id: 59,  fields: ["OD"],             options: [0, 1, 2, 3] },
  { id: 60,  fields: ["LP"],             options: [0, 1, 2, 3] },
  { id: 61,  fields: ["HY", "AH"],       options: [0, 1, 2, 3] },
  { id: 62,  fields: ["PR"],             options: [0, 1, 2, 3] },
  { id: 63,  fields: ["EF"],             options: [0, 1, 2, 3] },

  // ── Part 2 (Q64–108) ──────────────────────────────────────────
  { id: 64,  fields: ["PR"],             options: [3, 2, 1, 0] },
  { id: 65,  fields: ["AG", "CD"],       options: [0, 1, 2, 3] },
  { id: 66,  fields: [],                 options: [0, 1, 2, 3] },
  { id: 67,  fields: ["IN", "GI"],       options: [0, 1, 2, 3] },
  { id: 68,  fields: ["AN"],             options: [0, 1, 2, 3] },
  { id: 69,  fields: ["HY", "AH"],       options: [0, 1, 2, 3] },
  { id: 70,  fields: [],                 options: [0, 1, 2, 3] },
  { id: 71,  fields: ["HY", "AH"],       options: [0, 1, 2, 3] },
  { id: 72,  fields: ["EF"],             options: [3, 2, 1, 0] },
  { id: 73,  fields: ["OD"],             options: [0, 1, 2, 3] },
  { id: 74,  fields: ["PI"],             options: [0, 0, 0, 1] },
  { id: 75,  fields: ["EF"],             options: [0, 1, 2, 3] },
  { id: 76,  fields: ["CD"],             options: [0, 1, 2, 3] },
  { id: 77,  fields: ["IN"],             options: [0, 1, 2, 3] },
  { id: 78,  fields: ["CD"],             options: [0, 1, 2, 3] },
  { id: 79,  fields: ["EF", "AN"],       options: [0, 1, 2, 3] },
  { id: 80,  fields: ["PI"],             options: [0, 0, 0, 1] },
  { id: 81,  fields: ["GI"],             options: [0, 1, 2, 3] },
  { id: 82,  fields: [],                 options: [0, 1, 2, 3] },
  { id: 83,  fields: ["AG"],             options: [0, 1, 2, 3] },
  { id: 84,  fields: ["EF", "AN"],       options: [0, 1, 2, 3] },
  { id: 85,  fields: ["GI"],             options: [0, 1, 2, 3] },
  { id: 86,  fields: ["AG"],             options: [0, 1, 2, 3] },
  { id: 87,  fields: ["LP"],             options: [0, 1, 2, 3] },
  { id: 88,  fields: ["IN"],             options: [0, 1, 2, 3] },
  { id: 89,  fields: ["CD"],             options: [0, 1, 2, 3] },
  { id: 90,  fields: ["EF"],             options: [0, 1, 2, 3] },
  { id: 91,  fields: ["CD"],             options: [0, 1, 2, 3] },
  { id: 92,  fields: ["PR"],             options: [0, 1, 2, 3] },
  { id: 93,  fields: ["HY", "AH"],       options: [0, 1, 2, 3] },
  { id: 94,  fields: ["AG", "OD"],       options: [0, 1, 2, 3] },
  { id: 95,  fields: ["IN", "AN"],       options: [0, 1, 2, 3] },
  { id: 96,  fields: ["CD"],             options: [0, 1, 2, 3] },
  { id: 97,  fields: ["EF", "AN"],       options: [0, 1, 2, 3] },
  { id: 98,  fields: ["HY", "AH"],       options: [0, 1, 2, 3] },
  { id: 99,  fields: ["HY", "GI", "AH"], options: [0, 1, 2, 3] },
  { id: 100, fields: [],                 options: [0, 1, 2, 3] },
  { id: 101, fields: ["AN"],             options: [0, 1, 2, 3] },
  { id: 102, fields: ["AG", "OD"],       options: [0, 1, 2, 3] },
  { id: 103, fields: [],                 options: [0, 1, 2, 3] },
  { id: 104, fields: ["HY", "AH"],       options: [0, 1, 2, 3] },
  { id: 105, fields: ["PI"],             options: [0, 0, 0, 1] },
  { id: 106, fields: [],                 options: [0, 1, 2, 3] },
  { id: 107, fields: [],                 options: [0, 1, 2, 3] },
  { id: 108, fields: [],                 options: [0, 1, 2, 3] },
];

export default questions;
